### ISSUE TITLE
Blog page - Single

### ISSUE THREAD

**Issue by bohraji** [coloredcow-admin/glific-website#25]
Single blog page designs to be added.
Needed by date - 22 September 2020

**Comment by abhi1203** [comment]
- [ ] Since we haven't used these white blocks in the main blogs page, can we remove from here also. that will keep it consistent 
![image](https://user-images.githubusercontent.com/16714604/93778658-c1a44c80-fc43-11ea-8641-bc479b4a99a6.png)

- [ ] Please use sentence case
![image](https://user-images.githubusercontent.com/16714604/93778737-dc76c100-fc43-11ea-9a00-6f4ae27695d3.png)

- [ ] Align these button and input field
![image](https://user-images.githubusercontent.com/16714604/93778859-f6180880-fc43-11ea-9ef7-0ebe52b6f7a1.png)

- [ ] What does this mean? Your email id will not be published? where is it getting published? and can we show in design how it will look
![image](https://user-images.githubusercontent.com/16714604/93778888-fdd7ad00-fc43-11ea-8f51-c5d51564ad32.png)

- [ ] Is there a better label than `Send`? Not sure where it is sending? Maybe Publish or Submit or Comment?
And then the heading change a little bit, Leave a comment maybe

- [ ] Please use consistent spacing
![image](https://user-images.githubusercontent.com/16714604/93779219-5a3acc80-fc44-11ea-8e70-1041880bef3e.png)

![image](https://user-images.githubusercontent.com/16714604/93779244-6030ad80-fc44-11ea-994c-e7739bde41bc.png)

![image](https://user-images.githubusercontent.com/16714604/93779255-63c43480-fc44-11ea-9ea4-3ec249a9c8c7.png)


- [ ] Can you check the grouping here, the date and title are not clickable in sketch cloud. I think it's cuz of masking, can we crop the image instead or maybe some other solution? like, putting the date and title layers above image.
![image](https://user-images.githubusercontent.com/16714604/93779445-9ff79500-fc44-11ea-9af1-3ecc53fec2ab.png)

- [ ] Please check the width of the text, it's going beyond the comment input box
![image](https://user-images.githubusercontent.com/16714604/93779756-ed740200-fc44-11ea-9c64-38f1c51654be.png)

- [ ] Sentence case, use small n
![image](https://user-images.githubusercontent.com/16714604/93779802-f8c72d80-fc44-11ea-8e32-e0fa93d6038a.png)

- [ ] can we find a better alignment of name and date
![image](https://user-images.githubusercontent.com/16714604/93779910-1dbba080-fc45-11ea-9b48-bc30e40ab2f3.png)
Also, why is date capital and name small? it appears that date is more important and name and hence is more highlighted.

- [ ] check the grey background in mobile
![image](https://user-images.githubusercontent.com/16714604/93780022-46439a80-fc45-11ea-8eba-33a95498906c.png)

- [ ] check if this is the right spacing we've used in other screens also
![image](https://user-images.githubusercontent.com/16714604/93780077-565b7a00-fc45-11ea-9068-5575e51bbb8c.png)

**Comment by bohraji** [comment]
Since the designs are done, closing the issue.
