### ISSUE TITLE
Header changes for resources link 

### ISSUE THREAD

**Issue by mohitgusain** [coloredcow-admin/glific-website#44]
1. Need to make submenu for the Resources link

**Comment by bohraji** [comment]
@mohitgusain the navbar is looking fine. However, on the mobile view, is it possible to open the submenu when clicking on the whole link rather than just the icon?

<img width="503" alt="Screenshot 2020-10-01 at 11 51 03 AM" src="https://user-images.githubusercontent.com/12884297/94775001-960c2980-03dc-11eb-9c18-07864ef22403.png">

**Comment by mohitgusain** [comment]
@bohraji We can make it for the resources page as the resources page does not have any link to the redirect. It will break in the future if we will add the submenus for any other link where the link will be present for that menu. In that case, the page will redirect to that link and will not open the submenu. Like if I will add the submenu for the features page, what action it will play, will open the feature page, or will open the submenu. Let me know your thoughts on it.

**Comment by bohraji** [comment]
Alright. Let's go with this for now.
